export {default as NotFoundPage} from './NotFoundPage'
export {default as DashboardPage} from './DashboardPage'
export {default as SalePage} from './SalePage'
export {default as LoginPage} from './LoginPage'
export {default as RegisterPage} from './RegisterPage'
